const ALL_PROJECTS = [
  {
    "id": 1,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Backyard concrete patio with broom finish and control joints. Properly sloped for drainage toward the yard.",
    "size": "120 sq ft",
    "budget": "$8k\u2013$12k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 20.4,
    "y": 14.8
  },
  {
    "id": 2,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Two-car driveway replacement. Widened 2 feet on each side. Proper drainage slope to street.",
    "size": "160 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 54.0,
    "y": 14.5
  },
  {
    "id": 3,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "180 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 18.2,
    "y": 74.4
  },
  {
    "id": 4,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Travertine-pattern stamped patio with buff color. Seamless with French door opening.",
    "size": "220 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 53.7,
    "y": 62.7
  },
  {
    "id": 5,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "260 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 74.0,
    "y": 48.7
  },
  {
    "id": 6,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "New patio extending from sliding glass door. Smooth trowel finish with decorative border.",
    "size": "300 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 19.2,
    "y": 25.9
  },
  {
    "id": 7,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Long single-lane driveway to detached garage. Broom finish with exposed aggregate edging.",
    "size": "340 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 53.6,
    "y": 21.7
  },
  {
    "id": 8,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "380 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 19.5,
    "y": 62.7
  },
  {
    "id": 9,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Ashlar slate stamped patio with charcoal integral color and light release agent.",
    "size": "420 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 49.7,
    "y": 64.7
  },
  {
    "id": 10,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "460 sq ft",
    "budget": "$2k\u2013$4k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 72.1,
    "y": 46.7
  },
  {
    "id": 11,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "L-shaped patio addition matching existing concrete. Includes built-in planter curb.",
    "size": "500 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 23.8,
    "y": 24.1
  },
  {
    "id": 12,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Driveway replacement with turnaround pad. Full demolition, new base, reinforced pour.",
    "size": "540 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 61.8,
    "y": 20.9
  },
  {
    "id": 13,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "580 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 8.7,
    "y": 64.8
  },
  {
    "id": 14,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Cobblestone stamped driveway with antiquing finish. Complements Victorian-era home exterior.",
    "size": "640 sq ft",
    "budget": "$12k\u2013$18k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 54.2,
    "y": 76.0
  },
  {
    "id": 15,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "700 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 81.8,
    "y": 41.3
  },
  {
    "id": 16,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Front entry patio with broom finish. Widened to accommodate outdoor seating area.",
    "size": "760 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 22.6,
    "y": 30.2
  },
  {
    "id": 17,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Full driveway replacement. 6-inch base, reinforced slab, broom finish. Permit handled.",
    "size": "820 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 64.0,
    "y": 18.4
  },
  {
    "id": 18,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "880 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 17.6,
    "y": 65.9
  },
  {
    "id": 19,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Random flagstone patio with two-tone color. Acid stain finish adds depth and character.",
    "size": "960 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 50.0,
    "y": 72.9
  },
  {
    "id": 20,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "1,050 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 80.2,
    "y": 43.3
  },
  {
    "id": 21,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Backyard concrete patio with broom finish and control joints. Properly sloped for drainage toward the yard.",
    "size": "120 sq ft",
    "budget": "$8k\u2013$12k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 14.1,
    "y": 21.8
  },
  {
    "id": 22,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Two-car driveway replacement. Widened 2 feet on each side. Proper drainage slope to street.",
    "size": "160 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 65.9,
    "y": 22.5
  },
  {
    "id": 23,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "180 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 18.4,
    "y": 73.6
  },
  {
    "id": 24,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Travertine-pattern stamped patio with buff color. Seamless with French door opening.",
    "size": "220 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 48.0,
    "y": 62.7
  },
  {
    "id": 25,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "260 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 76.9,
    "y": 41.7
  },
  {
    "id": 26,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "New patio extending from sliding glass door. Smooth trowel finish with decorative border.",
    "size": "300 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 24.2,
    "y": 19.4
  },
  {
    "id": 27,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Long single-lane driveway to detached garage. Broom finish with exposed aggregate edging.",
    "size": "340 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 56.4,
    "y": 26.9
  },
  {
    "id": 28,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "380 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 9.7,
    "y": 62.3
  },
  {
    "id": 29,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Ashlar slate stamped patio with charcoal integral color and light release agent.",
    "size": "420 sq ft",
    "budget": "$20k\u2013$30k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 53.3,
    "y": 66.4
  },
  {
    "id": 30,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "460 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 84.9,
    "y": 47.0
  },
  {
    "id": 31,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "L-shaped patio addition matching existing concrete. Includes built-in planter curb.",
    "size": "500 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 26.2,
    "y": 16.6
  },
  {
    "id": 32,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Driveway replacement with turnaround pad. Full demolition, new base, reinforced pour.",
    "size": "540 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 51.6,
    "y": 13.1
  },
  {
    "id": 33,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "580 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 9.8,
    "y": 62.7
  },
  {
    "id": 34,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Cobblestone stamped driveway with antiquing finish. Complements Victorian-era home exterior.",
    "size": "640 sq ft",
    "budget": "$20k\u2013$30k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 51.1,
    "y": 63.2
  },
  {
    "id": 35,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "700 sq ft",
    "budget": "$2k\u2013$4k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 80.0,
    "y": 48.1
  },
  {
    "id": 36,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Front entry patio with broom finish. Widened to accommodate outdoor seating area.",
    "size": "760 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 25.7,
    "y": 28.2
  },
  {
    "id": 37,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Full driveway replacement. 6-inch base, reinforced slab, broom finish. Permit handled.",
    "size": "820 sq ft",
    "budget": "$6k\u2013$10k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 61.0,
    "y": 14.1
  },
  {
    "id": 38,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "880 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 19.7,
    "y": 65.5
  },
  {
    "id": 39,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Random flagstone patio with two-tone color. Acid stain finish adds depth and character.",
    "size": "960 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 51.3,
    "y": 69.5
  },
  {
    "id": 40,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "1,050 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 86.1,
    "y": 52.8
  },
  {
    "id": 41,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Backyard concrete patio with broom finish and control joints. Properly sloped for drainage toward the yard.",
    "size": "120 sq ft",
    "budget": "$8k\u2013$12k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 24.8,
    "y": 28.3
  },
  {
    "id": 42,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Two-car driveway replacement. Widened 2 feet on each side. Proper drainage slope to street.",
    "size": "160 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 63.6,
    "y": 20.4
  },
  {
    "id": 43,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "180 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 9.8,
    "y": 72.3
  },
  {
    "id": 44,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Travertine-pattern stamped patio with buff color. Seamless with French door opening.",
    "size": "220 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 59.6,
    "y": 77.0
  },
  {
    "id": 45,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "260 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 80.1,
    "y": 48.4
  },
  {
    "id": 46,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "New patio extending from sliding glass door. Smooth trowel finish with decorative border.",
    "size": "300 sq ft",
    "budget": "$8k\u2013$12k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 25.1,
    "y": 28.5
  },
  {
    "id": 47,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Long single-lane driveway to detached garage. Broom finish with exposed aggregate edging.",
    "size": "340 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 53.9,
    "y": 16.2
  },
  {
    "id": 48,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "380 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 8.8,
    "y": 67.9
  },
  {
    "id": 49,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Ashlar slate stamped patio with charcoal integral color and light release agent.",
    "size": "420 sq ft",
    "budget": "$12k\u2013$18k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 59.9,
    "y": 70.7
  },
  {
    "id": 50,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "460 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 72.6,
    "y": 48.2
  },
  {
    "id": 51,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "L-shaped patio addition matching existing concrete. Includes built-in planter curb.",
    "size": "500 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 12.8,
    "y": 22.8
  },
  {
    "id": 52,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Driveway replacement with turnaround pad. Full demolition, new base, reinforced pour.",
    "size": "540 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 65.5,
    "y": 27.2
  },
  {
    "id": 53,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "580 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 18.8,
    "y": 66.5
  },
  {
    "id": 54,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Cobblestone stamped driveway with antiquing finish. Complements Victorian-era home exterior.",
    "size": "640 sq ft",
    "budget": "$20k\u2013$30k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 54.7,
    "y": 69.2
  },
  {
    "id": 55,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "700 sq ft",
    "budget": "$2k\u2013$4k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 72.4,
    "y": 44.2
  },
  {
    "id": 56,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Front entry patio with broom finish. Widened to accommodate outdoor seating area.",
    "size": "760 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 10.5,
    "y": 23.3
  },
  {
    "id": 57,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Full driveway replacement. 6-inch base, reinforced slab, broom finish. Permit handled.",
    "size": "820 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 50.2,
    "y": 23.6
  },
  {
    "id": 58,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "880 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 11.1,
    "y": 74.6
  },
  {
    "id": 59,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Random flagstone patio with two-tone color. Acid stain finish adds depth and character.",
    "size": "960 sq ft",
    "budget": "$20k\u2013$30k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 45.4,
    "y": 66.0
  },
  {
    "id": 60,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "1,050 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 73.9,
    "y": 42.7
  },
  {
    "id": 61,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Backyard concrete patio with broom finish and control joints. Properly sloped for drainage toward the yard.",
    "size": "120 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 19.4,
    "y": 18.3
  },
  {
    "id": 62,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Two-car driveway replacement. Widened 2 feet on each side. Proper drainage slope to street.",
    "size": "160 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 63.0,
    "y": 15.3
  },
  {
    "id": 63,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "180 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 17.9,
    "y": 65.8
  },
  {
    "id": 64,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Travertine-pattern stamped patio with buff color. Seamless with French door opening.",
    "size": "220 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 51.8,
    "y": 73.9
  },
  {
    "id": 65,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "260 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 71.5,
    "y": 52.3
  },
  {
    "id": 66,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "New patio extending from sliding glass door. Smooth trowel finish with decorative border.",
    "size": "300 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 14.2,
    "y": 17.4
  },
  {
    "id": 67,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Long single-lane driveway to detached garage. Broom finish with exposed aggregate edging.",
    "size": "340 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 52.3,
    "y": 15.2
  },
  {
    "id": 68,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "380 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 11.4,
    "y": 74.9
  },
  {
    "id": 69,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Ashlar slate stamped patio with charcoal integral color and light release agent.",
    "size": "420 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 57.2,
    "y": 75.9
  },
  {
    "id": 70,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "460 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 71.3,
    "y": 56.6
  },
  {
    "id": 71,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "L-shaped patio addition matching existing concrete. Includes built-in planter curb.",
    "size": "500 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 25.7,
    "y": 29.2
  },
  {
    "id": 72,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Driveway replacement with turnaround pad. Full demolition, new base, reinforced pour.",
    "size": "540 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 52.8,
    "y": 20.1
  },
  {
    "id": 73,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "580 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 21.2,
    "y": 74.5
  },
  {
    "id": 74,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Cobblestone stamped driveway with antiquing finish. Complements Victorian-era home exterior.",
    "size": "640 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 50.4,
    "y": 78.0
  },
  {
    "id": 75,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "700 sq ft",
    "budget": "$2k\u2013$4k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 85.3,
    "y": 53.2
  },
  {
    "id": 76,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Front entry patio with broom finish. Widened to accommodate outdoor seating area.",
    "size": "760 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 17.0,
    "y": 29.7
  },
  {
    "id": 77,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Full driveway replacement. 6-inch base, reinforced slab, broom finish. Permit handled.",
    "size": "820 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 52.6,
    "y": 17.0
  },
  {
    "id": 78,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "880 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 16.7,
    "y": 68.8
  },
  {
    "id": 79,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Random flagstone patio with two-tone color. Acid stain finish adds depth and character.",
    "size": "960 sq ft",
    "budget": "$20k\u2013$30k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 49.3,
    "y": 63.0
  },
  {
    "id": 80,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "1,050 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 78.5,
    "y": 54.2
  },
  {
    "id": 81,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Backyard concrete patio with broom finish and control joints. Properly sloped for drainage toward the yard.",
    "size": "120 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 11.1,
    "y": 22.5
  },
  {
    "id": 82,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Two-car driveway replacement. Widened 2 feet on each side. Proper drainage slope to street.",
    "size": "160 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 51.2,
    "y": 13.4
  },
  {
    "id": 83,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "180 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 13.9,
    "y": 75.2
  },
  {
    "id": 84,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Travertine-pattern stamped patio with buff color. Seamless with French door opening.",
    "size": "220 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 48.2,
    "y": 71.7
  },
  {
    "id": 85,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "260 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 77.2,
    "y": 49.9
  },
  {
    "id": 86,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "New patio extending from sliding glass door. Smooth trowel finish with decorative border.",
    "size": "300 sq ft",
    "budget": "$8k\u2013$12k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 15.3,
    "y": 18.6
  },
  {
    "id": 87,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Long single-lane driveway to detached garage. Broom finish with exposed aggregate edging.",
    "size": "340 sq ft",
    "budget": "$6k\u2013$10k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 53.9,
    "y": 18.6
  },
  {
    "id": 88,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "380 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 14.7,
    "y": 75.0
  },
  {
    "id": 89,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Ashlar slate stamped patio with charcoal integral color and light release agent.",
    "size": "420 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 44.4,
    "y": 72.1
  },
  {
    "id": 90,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "460 sq ft",
    "budget": "$2k\u2013$4k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 71.7,
    "y": 44.0
  },
  {
    "id": 91,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "L-shaped patio addition matching existing concrete. Includes built-in planter curb.",
    "size": "500 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 12.3,
    "y": 20.0
  },
  {
    "id": 92,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Driveway replacement with turnaround pad. Full demolition, new base, reinforced pour.",
    "size": "540 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 64.2,
    "y": 18.2
  },
  {
    "id": 93,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "580 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 14.4,
    "y": 68.8
  },
  {
    "id": 94,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Cobblestone stamped driveway with antiquing finish. Complements Victorian-era home exterior.",
    "size": "640 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 54.1,
    "y": 78.0
  },
  {
    "id": 95,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "700 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 81.2,
    "y": 49.5
  },
  {
    "id": 96,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Front entry patio with broom finish. Widened to accommodate outdoor seating area.",
    "size": "760 sq ft",
    "budget": "$8k\u2013$12k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 11.9,
    "y": 28.5
  },
  {
    "id": 97,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Full driveway replacement. 6-inch base, reinforced slab, broom finish. Permit handled.",
    "size": "820 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 51.9,
    "y": 14.0
  },
  {
    "id": 98,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "880 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 11.8,
    "y": 69.8
  },
  {
    "id": 99,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Random flagstone patio with two-tone color. Acid stain finish adds depth and character.",
    "size": "960 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 49.8,
    "y": 73.2
  },
  {
    "id": 100,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "1,050 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 78.6,
    "y": 44.6
  },
  {
    "id": 101,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Backyard concrete patio with broom finish and control joints. Properly sloped for drainage toward the yard.",
    "size": "120 sq ft",
    "budget": "$8k\u2013$12k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 11.7,
    "y": 21.2
  },
  {
    "id": 102,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Two-car driveway replacement. Widened 2 feet on each side. Proper drainage slope to street.",
    "size": "160 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 50.8,
    "y": 17.6
  },
  {
    "id": 103,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "180 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 17.6,
    "y": 64.3
  },
  {
    "id": 104,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Travertine-pattern stamped patio with buff color. Seamless with French door opening.",
    "size": "220 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 51.4,
    "y": 73.5
  },
  {
    "id": 105,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "260 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 72.3,
    "y": 55.7
  },
  {
    "id": 106,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "New patio extending from sliding glass door. Smooth trowel finish with decorative border.",
    "size": "300 sq ft",
    "budget": "$8k\u2013$12k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 24.7,
    "y": 23.1
  },
  {
    "id": 107,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Long single-lane driveway to detached garage. Broom finish with exposed aggregate edging.",
    "size": "340 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 59.4,
    "y": 14.7
  },
  {
    "id": 108,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "380 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 8.1,
    "y": 65.9
  },
  {
    "id": 109,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Ashlar slate stamped patio with charcoal integral color and light release agent.",
    "size": "420 sq ft",
    "budget": "$12k\u2013$18k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 58.7,
    "y": 65.6
  },
  {
    "id": 110,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "460 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 81.2,
    "y": 46.3
  },
  {
    "id": 111,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "L-shaped patio addition matching existing concrete. Includes built-in planter curb.",
    "size": "500 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 24.3,
    "y": 20.9
  },
  {
    "id": 112,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Driveway replacement with turnaround pad. Full demolition, new base, reinforced pour.",
    "size": "540 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 64.9,
    "y": 16.1
  },
  {
    "id": 113,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "580 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 23.0,
    "y": 73.1
  },
  {
    "id": 114,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Cobblestone stamped driveway with antiquing finish. Complements Victorian-era home exterior.",
    "size": "640 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 44.7,
    "y": 74.0
  },
  {
    "id": 115,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "700 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 83.0,
    "y": 47.2
  },
  {
    "id": 116,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Front entry patio with broom finish. Widened to accommodate outdoor seating area.",
    "size": "760 sq ft",
    "budget": "$8k\u2013$12k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 24.0,
    "y": 27.4
  },
  {
    "id": 117,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Full driveway replacement. 6-inch base, reinforced slab, broom finish. Permit handled.",
    "size": "820 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 52.6,
    "y": 23.5
  },
  {
    "id": 118,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "880 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 21.4,
    "y": 73.8
  },
  {
    "id": 119,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Random flagstone patio with two-tone color. Acid stain finish adds depth and character.",
    "size": "960 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 47.5,
    "y": 76.9
  },
  {
    "id": 120,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "1,050 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 75.4,
    "y": 53.3
  },
  {
    "id": 121,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Backyard concrete patio with broom finish and control joints. Properly sloped for drainage toward the yard.",
    "size": "120 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 13.8,
    "y": 25.0
  },
  {
    "id": 122,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Two-car driveway replacement. Widened 2 feet on each side. Proper drainage slope to street.",
    "size": "160 sq ft",
    "budget": "$6k\u2013$10k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 55.4,
    "y": 26.1
  },
  {
    "id": 123,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "180 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 13.0,
    "y": 68.3
  },
  {
    "id": 124,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Travertine-pattern stamped patio with buff color. Seamless with French door opening.",
    "size": "220 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 60.0,
    "y": 70.8
  },
  {
    "id": 125,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "260 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 72.3,
    "y": 56.1
  },
  {
    "id": 126,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "New patio extending from sliding glass door. Smooth trowel finish with decorative border.",
    "size": "300 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 19.5,
    "y": 30.1
  },
  {
    "id": 127,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Long single-lane driveway to detached garage. Broom finish with exposed aggregate edging.",
    "size": "340 sq ft",
    "budget": "$6k\u2013$10k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 51.8,
    "y": 19.3
  },
  {
    "id": 128,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "380 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 14.4,
    "y": 75.8
  },
  {
    "id": 129,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Ashlar slate stamped patio with charcoal integral color and light release agent.",
    "size": "420 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 50.5,
    "y": 71.4
  },
  {
    "id": 130,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "460 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 71.2,
    "y": 47.6
  },
  {
    "id": 131,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "L-shaped patio addition matching existing concrete. Includes built-in planter curb.",
    "size": "500 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 25.0,
    "y": 23.0
  },
  {
    "id": 132,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Driveway replacement with turnaround pad. Full demolition, new base, reinforced pour.",
    "size": "540 sq ft",
    "budget": "$6k\u2013$10k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 55.9,
    "y": 13.4
  },
  {
    "id": 133,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "580 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 17.4,
    "y": 70.7
  },
  {
    "id": 134,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Cobblestone stamped driveway with antiquing finish. Complements Victorian-era home exterior.",
    "size": "640 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 55.8,
    "y": 67.0
  },
  {
    "id": 135,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "700 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 81.2,
    "y": 45.8
  },
  {
    "id": 136,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Front entry patio with broom finish. Widened to accommodate outdoor seating area.",
    "size": "760 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 14.9,
    "y": 16.4
  },
  {
    "id": 137,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Full driveway replacement. 6-inch base, reinforced slab, broom finish. Permit handled.",
    "size": "820 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 60.7,
    "y": 18.4
  },
  {
    "id": 138,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "880 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 17.2,
    "y": 64.9
  },
  {
    "id": 139,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Random flagstone patio with two-tone color. Acid stain finish adds depth and character.",
    "size": "960 sq ft",
    "budget": "$12k\u2013$18k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 57.6,
    "y": 67.1
  },
  {
    "id": 140,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "1,050 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 77.4,
    "y": 49.9
  },
  {
    "id": 141,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Backyard concrete patio with broom finish and control joints. Properly sloped for drainage toward the yard.",
    "size": "120 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 15.4,
    "y": 21.5
  },
  {
    "id": 142,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Two-car driveway replacement. Widened 2 feet on each side. Proper drainage slope to street.",
    "size": "160 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 58.3,
    "y": 25.0
  },
  {
    "id": 143,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "180 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 17.9,
    "y": 64.6
  },
  {
    "id": 144,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Travertine-pattern stamped patio with buff color. Seamless with French door opening.",
    "size": "220 sq ft",
    "budget": "$12k\u2013$18k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 54.4,
    "y": 67.6
  },
  {
    "id": 145,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "260 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 81.3,
    "y": 44.2
  },
  {
    "id": 146,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "New patio extending from sliding glass door. Smooth trowel finish with decorative border.",
    "size": "300 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 12.6,
    "y": 15.1
  },
  {
    "id": 147,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Long single-lane driveway to detached garage. Broom finish with exposed aggregate edging.",
    "size": "340 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 59.9,
    "y": 24.6
  },
  {
    "id": 148,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "380 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 14.0,
    "y": 70.2
  },
  {
    "id": 149,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Ashlar slate stamped patio with charcoal integral color and light release agent.",
    "size": "420 sq ft",
    "budget": "$20k\u2013$30k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 55.8,
    "y": 68.3
  },
  {
    "id": 150,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "460 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 74.4,
    "y": 51.1
  },
  {
    "id": 151,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "L-shaped patio addition matching existing concrete. Includes built-in planter curb.",
    "size": "500 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 24.5,
    "y": 28.2
  },
  {
    "id": 152,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Driveway replacement with turnaround pad. Full demolition, new base, reinforced pour.",
    "size": "540 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 62.6,
    "y": 15.8
  },
  {
    "id": 153,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "580 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 8.2,
    "y": 64.1
  },
  {
    "id": 154,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Cobblestone stamped driveway with antiquing finish. Complements Victorian-era home exterior.",
    "size": "640 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 51.6,
    "y": 75.0
  },
  {
    "id": 155,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "700 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 85.7,
    "y": 54.9
  },
  {
    "id": 156,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Front entry patio with broom finish. Widened to accommodate outdoor seating area.",
    "size": "760 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 23.2,
    "y": 28.7
  },
  {
    "id": 157,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Full driveway replacement. 6-inch base, reinforced slab, broom finish. Permit handled.",
    "size": "820 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 63.4,
    "y": 21.1
  },
  {
    "id": 158,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "880 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 19.3,
    "y": 67.7
  },
  {
    "id": 159,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Random flagstone patio with two-tone color. Acid stain finish adds depth and character.",
    "size": "960 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 56.3,
    "y": 75.6
  },
  {
    "id": 160,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "1,050 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 82.8,
    "y": 48.9
  },
  {
    "id": 161,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Backyard concrete patio with broom finish and control joints. Properly sloped for drainage toward the yard.",
    "size": "120 sq ft",
    "budget": "$8k\u2013$12k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 14.0,
    "y": 21.4
  },
  {
    "id": 162,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Two-car driveway replacement. Widened 2 feet on each side. Proper drainage slope to street.",
    "size": "160 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 53.9,
    "y": 17.7
  },
  {
    "id": 163,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "180 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 9.6,
    "y": 63.8
  },
  {
    "id": 164,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Travertine-pattern stamped patio with buff color. Seamless with French door opening.",
    "size": "220 sq ft",
    "budget": "$20k\u2013$30k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 46.7,
    "y": 65.6
  },
  {
    "id": 165,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "260 sq ft",
    "budget": "$2k\u2013$4k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 77.0,
    "y": 49.3
  },
  {
    "id": 166,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "New patio extending from sliding glass door. Smooth trowel finish with decorative border.",
    "size": "300 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 11.2,
    "y": 27.7
  },
  {
    "id": 167,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Long single-lane driveway to detached garage. Broom finish with exposed aggregate edging.",
    "size": "340 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 64.6,
    "y": 21.6
  },
  {
    "id": 168,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "380 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 21.1,
    "y": 72.3
  },
  {
    "id": 169,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Ashlar slate stamped patio with charcoal integral color and light release agent.",
    "size": "420 sq ft",
    "budget": "$16k\u2013$24k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 51.9,
    "y": 77.3
  },
  {
    "id": 170,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "460 sq ft",
    "budget": "$2k\u2013$4k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 82.6,
    "y": 54.3
  },
  {
    "id": 171,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "L-shaped patio addition matching existing concrete. Includes built-in planter curb.",
    "size": "500 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 18.8,
    "y": 26.2
  },
  {
    "id": 172,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Driveway replacement with turnaround pad. Full demolition, new base, reinforced pour.",
    "size": "540 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 57.9,
    "y": 16.7
  },
  {
    "id": 173,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "580 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 7.9,
    "y": 65.5
  },
  {
    "id": 174,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Cobblestone stamped driveway with antiquing finish. Complements Victorian-era home exterior.",
    "size": "640 sq ft",
    "budget": "$20k\u2013$30k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 57.1,
    "y": 73.8
  },
  {
    "id": 175,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "700 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 85.2,
    "y": 56.3
  },
  {
    "id": 176,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Front entry patio with broom finish. Widened to accommodate outdoor seating area.",
    "size": "760 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 10.6,
    "y": 20.7
  },
  {
    "id": 177,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Full driveway replacement. 6-inch base, reinforced slab, broom finish. Permit handled.",
    "size": "820 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 51.4,
    "y": 19.2
  },
  {
    "id": 178,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "880 sq ft",
    "budget": "$4k\u2013$7k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 10.3,
    "y": 64.3
  },
  {
    "id": 179,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Random flagstone patio with two-tone color. Acid stain finish adds depth and character.",
    "size": "960 sq ft",
    "budget": "$20k\u2013$30k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 47.7,
    "y": 67.4
  },
  {
    "id": 180,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "1,050 sq ft",
    "budget": "$2k\u2013$4k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 75.0,
    "y": 55.8
  },
  {
    "id": 181,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Backyard concrete patio with broom finish and control joints. Properly sloped for drainage toward the yard.",
    "size": "120 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 14.2,
    "y": 15.7
  },
  {
    "id": 182,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Two-car driveway replacement. Widened 2 feet on each side. Proper drainage slope to street.",
    "size": "160 sq ft",
    "budget": "$6k\u2013$10k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 62.1,
    "y": 13.1
  },
  {
    "id": 183,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "180 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 11.0,
    "y": 61.2
  },
  {
    "id": 184,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Travertine-pattern stamped patio with buff color. Seamless with French door opening.",
    "size": "220 sq ft",
    "budget": "$12k\u2013$18k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 44.9,
    "y": 62.7
  },
  {
    "id": 185,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "260 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 73.7,
    "y": 40.9
  },
  {
    "id": 186,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "New patio extending from sliding glass door. Smooth trowel finish with decorative border.",
    "size": "300 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 14.0,
    "y": 22.0
  },
  {
    "id": 187,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Long single-lane driveway to detached garage. Broom finish with exposed aggregate edging.",
    "size": "340 sq ft",
    "budget": "$6k\u2013$10k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 59.1,
    "y": 15.8
  },
  {
    "id": 188,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "3-car garage floor reslab. Control joints placed to manage seasonal movement. Seamless result.",
    "size": "380 sq ft",
    "budget": "$5k\u2013$8k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 19.7,
    "y": 62.8
  },
  {
    "id": 189,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Ashlar slate stamped patio with charcoal integral color and light release agent.",
    "size": "420 sq ft",
    "budget": "$12k\u2013$18k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 59.7,
    "y": 73.7
  },
  {
    "id": 190,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Front entry walkway from driveway to door. Broom finish, proper step height at threshold.",
    "size": "460 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 85.9,
    "y": 42.3
  },
  {
    "id": 191,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "L-shaped patio addition matching existing concrete. Includes built-in planter curb.",
    "size": "500 sq ft",
    "budget": "$10k\u2013$16k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 25.1,
    "y": 23.6
  },
  {
    "id": 192,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Driveway replacement with turnaround pad. Full demolition, new base, reinforced pour.",
    "size": "540 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 56.4,
    "y": 23.7
  },
  {
    "id": 193,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor replacement with vapor barrier and 4-inch reinforced slab. Smooth trowel finish.",
    "size": "580 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 16.9,
    "y": 73.4
  },
  {
    "id": 194,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Cobblestone stamped driveway with antiquing finish. Complements Victorian-era home exterior.",
    "size": "640 sq ft",
    "budget": "$8k\u2013$14k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 45.9,
    "y": 74.6
  },
  {
    "id": 195,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Public sidewalk replacement. City-spec compliant panels. Permit and inspection handled.",
    "size": "700 sq ft",
    "budget": "$1k\u2013$3k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 83.2,
    "y": 49.7
  },
  {
    "id": 196,
    "type": "patio",
    "title": "Concrete Patio \u2014 Crystal Lake",
    "city": "Crystal Lake, IL",
    "desc": "Front entry patio with broom finish. Widened to accommodate outdoor seating area.",
    "size": "760 sq ft",
    "budget": "$8k\u2013$12k",
    "img": "images/patio1.jpg",
    "link": "concrete-patio.html",
    "x": 15.8,
    "y": 21.3
  },
  {
    "id": 197,
    "type": "driveway",
    "title": "Concrete Driveway \u2014 Woodstock",
    "city": "Woodstock, IL",
    "desc": "Full driveway replacement. 6-inch base, reinforced slab, broom finish. Permit handled.",
    "size": "820 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/driveway1.jpg",
    "link": "concrete-driveway-replacement.html",
    "x": 51.2,
    "y": 22.7
  },
  {
    "id": 198,
    "type": "garage",
    "title": "Garage Floor \u2014 Cary",
    "city": "Cary, IL",
    "desc": "Garage floor with epoxy-ready surface. Fine broom texture, properly sloped to drain.",
    "size": "880 sq ft",
    "budget": "$3k\u2013$5k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 21.0,
    "y": 73.3
  },
  {
    "id": 199,
    "type": "stamped",
    "title": "Stamped Concrete \u2014 Algonquin",
    "city": "Algonquin, IL",
    "desc": "Random flagstone patio with two-tone color. Acid stain finish adds depth and character.",
    "size": "960 sq ft",
    "budget": "$20k\u2013$30k",
    "img": "images/stamped1.jpg",
    "link": "stamped-concrete.html",
    "x": 51.2,
    "y": 68.0
  },
  {
    "id": 200,
    "type": "sidewalk",
    "title": "Sidewalk & Walkway \u2014 Lake in the Hills",
    "city": "Lake in the Hills, IL",
    "desc": "Side walkway connecting driveway to back gate. Clean transitions at both ends.",
    "size": "1,050 sq ft",
    "budget": "$3k\u2013$6k",
    "img": "images/slab1.jpg",
    "link": "concrete-pads.html",
    "x": 81.8,
    "y": 47.6
  }
];